image:
  file: .gitpod/Dockerfile

ports:
  - port: 8000
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
  - port: 33060
    onOpen: ignore

tasks:
  - name: Server
    init: composer install && composer dump-autoload && git submodule update --init && mysql -u root -e "create database bugtracker" && cp .gitpod/config_inc.php ./config/ && php ./admin/upgrade_unattended.php
    command: php -S 0.0.0.0:8000
