image:
  file: .gitpod/Dockerfile

ports:
  - port: 8000
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
  - port: 33060
    onOpen: ignore

tasks:
  - name: Server
    init: composer install && composer dump-autoload && git submodule update --init && cp .gitpod/config_inc.php ./config/ && gp await-port 3306 && ./.gitpod/setup-db.sh
    command: php -S 0.0.0.0:8000
  - name: DevCli

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false

