image:
  file: .gitpod/Dockerfile

ports:
  - port: 8000
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
  - port: 33060
    onOpen: ignore

tasks:
  - name: Server
    init: composer install && composer dump-autoload && git submodule update --init && echo "Creating database..." && sleep 5 && mysql -u root -e "create database bugtracker" && cp .gitpod/config_inc.php ./config/ && php ./admin/upgrade_unattended.php && mysql -u root bugtracker -e "INSERT INTO mantis_project_table (name, enabled, view_state, access_min, category_id, inherit_global) VALUES ('Test', 1, 10, 10, 1, 1)"
    command: php -S 0.0.0.0:8000
